version: "3.9"

services:
  postgres:
    build:
      context: ./pnn_monitoring_database/
      dockerfile: Dockerfile
    networks:
      pnn_network:
        ipv4_address: 192.168.1.2
    environment:
      - POSTGRES_DB=pnn
      - POSTGRES_USER=pnn_user
      - POSTGRES_PASSWORD=123
    restart: always
    ports:
      - "5432:5432"

  python_app:
    build:
      context: ./pnn_monitoring_etl/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - pnn_network

networks:
  pnn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
