version: "3.9"

services:
  postgres:
    build:
      context: ./pnn_monitoring_database/
      dockerfile: Dockerfile
    networks:
      pnn_network:
        ipv4_address: 192.168.1.2
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "5432:5432"

  python_app:
    build:
      context: ./pnn_monitoring_etl/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=192.168.1.2
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
    volumes:
      - ${WORKSPACE_PATH}:/workdir/workspace/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - pnn_network

networks:
  pnn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
